version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0.28
    container_name: super-app-mysql
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - super-app-network
    restart: unless-stopped

  # Node.js Application Service
  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: super-app-node
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=super-app
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - super-app-network
    restart: unless-stopped

  # PHP Application Service
  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: super-app-php
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=super-app
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - super-app-network
    restart: unless-stopped

# Define custom network
networks:
  super-app-network:
    driver: bridge

# Define volumes for data persistence
volumes:
  mysql_data: