name: CI/CD Pipeline - Super App

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build and push Node.js application
          uses: docker/build-push-action@v5
          with:
            context: ./node
            file: ./node/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/super-app-node:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/super-app-node:${{ github.sha }}
            
        - name: Build and push PHP application
          uses: docker/build-push-action@v5
          with:
            context: ./php
            file: ./php/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/super-app-php:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/super-app-php:${{ github.sha }}
        
        - name: Build status
          run: |
            echo "✅ Node.js image: ${{ secrets.DOCKERHUB_USERNAME }}/super-app-node:latest"
            echo "✅ PHP image: ${{ secrets.DOCKERHUB_USERNAME }}/super-app-php:latest"
            echo "🚀 Images successfully pushed to DockerHub!"